@include('frontend.include.head')
@include('frontend.include.header')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="heading">Terms & Conditions</h3>
            <h4></h4>
            
            <p align="justify">www.nestoronline.in, an internet based portal is operated by Nestor Pharmaceuticals Limited, 
			a company duly incorporated under the provisions of the Indian Companies Act.</p>
            <br>
            <p align="justify">Use of the Website is offered to You, subject to acceptance of all the terms, conditions and notices contained in these Terms and Conditions including applicable policies which are incorporated herein by reference, along with any amendments / modifications made by Company at its sole discretion and posted on the Website, including by way of imposing an additional charge for access to or use of a service(s).
For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Account Information while registering on the Website as a registered User using the computer systems.
Company shall not be required to notify You, whether as a registered user or not, of any changes made to the Terms. The revised Terms shall be made available on the Website. Your use of the Website and the Services is subject to the most current version of the Terms made available on the Website, at the time of such use. You are requested to regularly visit the Website to view the most current Terms. It shall be your responsibility to check the Terms periodically for changes. Company may require You to provide your consent to the updated Terms in a specified manner prior to any further use of the Website and the Services, provided on the Website. If no such separate consent is sought, your continued use of the Website, following changes to the Terms, will constitute your express acceptance of those changes.</p>
  
<p align="justify">By using this Website or any facility or service provided by this Website in any way; or merely browsing the Website, you agree that you have read, understood and agreed to be bound by, including without limitation, these Terms, the Website's Privacy Policy, and such other rules, guidelines, policies, terms and conditions as are relevant under the applicable law(s) in India and other jurisdictions for the purposes of accessing, browsing or transacting on the Website, or availing any of the Services, and such rules, guidelines, policies, terms and conditions shall be deemed to be incorporated into, and considered as part and parcel of these Terms of Use. Company shall not be liable to deliver any Products purchased by you for delivery, in locations outside India or to remote areas with no courier coverage for door delivery.</p>  

<h4>USE OF CONTENT</h4>
<p align="justify">Except as expressly indicated to the contrary in any applicable additional terms, Company hereby grants You a personal, non-exclusive, freely revocable (upon notice from Company), non-transferable access to view any materials available on the Website, subject to the following condition:</p>
<p align="justify">1.You may access and use the materials solely for personal, informational, and internal purposes, in accordance with the Terms;</p>
<p align="justify">2.You may not modify or alter any materials available on the Website;<p>
<p align="justify">3.You may not distribute or sell, rent, lease, license or otherwise make any materials available on the Website available to others; and</p>
<p align="justify">4.You may not remove any text, copyright or other proprietary notices contained in any materials available on the Website.</p>
 <p align="justify">The rights granted to You in the use of any materials as specified above are not applicable to the design, layout or look and feel of the Website. Such elements of the Website are protected by intellectual property rights and may not be copied or imitated in whole or in part. Any materials available on the Website shall not be copied or retransmitted unless expressly permitted by Company.</p>
 <p align="justify">Any software that is available on the Website is the property of Company or its third parties. You may not use, download or install any software available at the Website, unless otherwise expressly permitted by these Terms or by the express written permission of Company.</p>
 <p align="justify">The User shall solely be responsible for maintaining the necessary computer equipments and Internet connections that may be required to access, use and transact on the Website.</p>
 <p align="justify">The User is also under an obligation to use this Website for reasonable and lawful purposes only, and shall not indulge in any activity that is not envisaged through the Website.</p>
 <p align="justify">The User shall use this Website, and any voucher/ coupons purchased/gifted through it, for personal, non-commercial use only and shall not re-sell the same to any other person.</p>
 
 <h4>INTELECTUAL PROPERTY RIGHTS</h4>
 <P align="justify">The Website and the processes, and their selection and arrangement, including but not limited to all text, graphics, user interfaces, visual interfaces, sounds and music (if any), artwork and computer code (collectively, the "Content") on the Website is owned and controlled by Company and the design, structure, selection, coordination, expression, look and feel and arrangement of such Content is protected by copyright, patent and trademark laws, and various other intellectual property rights.</p>
 <p align="justify">The trademarks, logos and service marks displayed on the Website("Marks") are the property of Company or their third parties or respective third parties. You are not permitted to use the Marks without the prior consent of Company, the relevant third parties that may own the Marks.</p>
 <p align="justify">Unless otherwise indicated or anything contained to the contrary, Company owns all intellectual property rights to and into the trademark www.nestoronline.in and the Website, including, without limitation, any and all rights, title and interest in and to copyright, related rights, patents, utility models, designs, know-how, trade secrets and inventions, goodwill, source code, meta tags, databases, text, content, graphics, icons, and hyperlinks.</p>
 <p align="justify">Except as expressly provided herein, You acknowledge and agree that You shall not copy, republish, post, display, translate, transmit, reproduce or distribute any Content through any medium without obtaining the necessary authorization from Company or third party owner of such Content.
</p>
<h4>DISCLAIMER OF WARRANNTIES & LIABILITIES</h4>
<p align="justify">You expressly understand and agree that, to the maximum extent permitted by applicable law:
the website, services and other materials are provided by Company on an "as is" basis without warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose. without limiting the foregoing, Company makes no warranty that (i) the Website or the services will meet your requirements or your use of the Website or the services will be uninterrupted, timely, secure or error-free; (ii) the results that may be obtained from the use of the Website, services or materials will be effective, accurate or reliable; (iii) the quality of the Website, services or other materials will meet your expectations; or that (iv) any errors or defects in the Website, services or other materials will be corrected. No advice or information, whether oral or written, obtained by you from Company or through or from use of the services shall create any warranty not expressly stated in the terms.
To the maximum extent permitted by applicable law, Company will have no liability related to user content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws. Company also disclaims all liability with respect to the misuse, loss, modification or unavailability of any user content.</p>

<h4>Disclaimer of Warranties & Liabilities</h4>
<p align="justify">You expressly understand and agree that, to the maximum extent permitted by applicable law:
the website, services and other materials are provided by Company on an "as is" basis without warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose. without limiting the foregoing, Company makes no warranty that (i) the Website or the services will meet your requirements or your use of the Website or the services will be uninterrupted, timely, secure or error-free; (ii) the results that may be obtained from the use of the Website, services or materials will be effective, accurate or reliable; (iii) the quality of the Website, services or other materials will meet your expectations; or that (iv) any errors or defects in the Website, services or other materials will be corrected. No advice or information, whether oral or written, obtained by you from Company or through or from use of the services shall create any warranty not expressly stated in the terms.
To the maximum extent permitted by applicable law, Company will have no liability related to user content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws. Company also disclaims all liability with respect to the misuse, loss, modification or unavailability of any user content.
Company will not be liable for any loss that you may incur as a consequence of unauthorized use of your Account or Account information in connection with the Website or any services or materials, either with or without your knowledge. Company has endeavoured to ensure that all the information on the Website is correct, but Company neither warrants nor makes any representations regarding the quality, accuracy or completeness of any data, information, product or service. Company shall not be responsible for the delay or inability to use the website or related functionalities, the provision of or failure to provide functionalities, or for any information, software, products, functionalities and related graphics obtained through the Website, or otherwise arising out of the use of the Website, whether based on contract, tort, negligence, strict liability or otherwise. further, Company shall not be held responsible for non-availability of the website during periodic maintenance operations or any unplanned suspension of access to the website that may occur due to technical reasons or for any reason beyond Company's control. The user understands and agrees that any material or data downloaded or otherwise obtained through the Website is done entirely at their own discretion and risk and they will be solely responsible for any damage to their computer systems or loss of data that results from the download of such material or data. Company is not responsible for any typographical error leading to an invalid coupon. Company accepts no liability for any errors or omissions, with respect to any information provided to you.
You expressly agree that your use of the Website is at your risk.</p>

<h4>Indemnification and Limitation of Liability</h4>
<p align="justify">You agree to indemnify, defend and hold harmless Company including but not limited to its affiliates, vendors, agents and employees from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Company that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by You pursuant to these Terms.
Notwithstanding anything to contrary, Company's entire liability to You under this Terms or otherwise shall be the refund of the money charged from You for any specific voucher or Product or service, under which the unlikely liability arises.
In no event shall Company, its officers, directors, employees, partners or suppliers be liable to You, for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not Company has been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortious action, or any other claim arising out of or in connection with your use of or access to the Website, services or materials.
The limitations and exclusions in this section apply to the maximum extent permitted by applicable law.</p>

<h4>Violation of the Terms
</h4>
<p align="justify">You agree that Company may, in its sole discretion and without prior notice, terminate your access to the Website and block your future access to the Website if Company determines that You have violated these Terms or additional terms. You also agree that any violation by You of these Terms will constitute an unlawful and unfair business practice, and will cause irreparable harm to Company, for which monetary damages would be inadequate, and You consent to Company obtaining any injunctive or equitable relief that Company deems necessary or appropriate in such circumstances. These remedies are in addition to any other remedies Company may have at law or in equity.
You agree that Company may, in its sole discretion, and without prior notice, terminate your access to the Website, for cause, which includes (but is not limited to): (1) requests by law enforcement or other government agencies; (2) a request by You (self-initiated account deletions); (3) discontinuance or material modification of the Website or any service offered on or through the Website; or (4) unexpected technical issues or problems.
If Company does take any legal action against You as a result of your violation of these Terms, Company will be entitled to recover from You, and You agree to pay, all reasonable attorneys' fees and costs of such action, in addition to any other relief granted to Company.</p>
 </div>
    </div>
</div>
@include('frontend.include.footer')